name: Verify No SNAPSHOT dependencies
description: Verifies that the maven pom file has no SNAPSHOT dependencies. This dependent on a runner/repository using MVN
runs:
  using: node13
  main: dist/index.js
